# Generated by Django 4.2.11 on 2024-04-02 11:38

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_rtfbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='rtfbody',
        ),
        migrations.AddField(
            model_name='homepage',
            name='cat_image',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
