# Generated by Django 4.2.11 on 2024-04-02 12:34

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_rtfbody_homepage_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cats_image',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
