# Generated by Django 4.2.11 on 2024-04-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_cats_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cat_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cats_image',
        ),
    ]
