# Generated by Django 4.2.11 on 2024-04-05 07:27

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_cat_image_remove_homepage_cats_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_field',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
