# Generated by Django 4.2.11 on 2024-04-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_text_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='text_field',
        ),
    ]
