# Generated by Django 4.2.11 on 2024-04-07 10:34

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rtf_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
